services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env.example
    environment:
      POSTGRES_DB: project_management_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U postgres -d project_management_system"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    env_file: .env.example
    environment:
      # Overwrite the url for Docker
      DB_URL: jdbc:postgresql://db:5432/project_management_system
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
